//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SOAPServices.validaDOC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="urn:ValidaDOCwsdl", ConfigurationName="validaDOC.ValidaDOCwsdlPortType")]
    public interface ValidaDOCwsdlPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:ValidaDNIwsdl) del mensaje validaDNIRequest no coincide con el valor predeterminado (urn:ValidaDOCwsdl)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ValidaDNIwsdl#ValidaDNI", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SOAPServices.validaDOC.validaDNIResponse validaDNI(SOAPServices.validaDOC.validaDNIRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ValidaDNIwsdl#ValidaDNI", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPServices.validaDOC.validaDNIResponse> validaDNIAsync(SOAPServices.validaDOC.validaDNIRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el espacio de nombres de contenedor (urn:ValidaRUCwsdl) del mensaje validaRUCRequest no coincide con el valor predeterminado (urn:ValidaDOCwsdl)
        [System.ServiceModel.OperationContractAttribute(Action="urn:ValidaRUCwsdl#ValidaRUC", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(Style=System.ServiceModel.OperationFormatStyle.Rpc, SupportFaults=true, Use=System.ServiceModel.OperationFormatUse.Encoded)]
        SOAPServices.validaDOC.validaRUCResponse validaRUC(SOAPServices.validaDOC.validaRUCRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="urn:ValidaRUCwsdl#ValidaRUC", ReplyAction="*")]
        System.Threading.Tasks.Task<SOAPServices.validaDOC.validaRUCResponse> validaRUCAsync(SOAPServices.validaDOC.validaRUCRequest request);
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ValidaDOCwsdl")]
    public partial class dniDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numrucField;
        
        private string razocField;
        
        private string estado_contField;
        
        private string condi_domField;
        
        private string ubigeoField;
        
        private string tipo_viaField;
        
        private string nom_viaField;
        
        private string cod_zonaField;
        
        private string tipo_zonaField;
        
        private string numeroField;
        
        private string interiorField;
        
        private string loteField;
        
        private string departamentoField;
        
        private string manzanaField;
        
        private string kilometroField;
        
        private string statusField;
        
        private string dniField;
        
        /// <comentarios/>
        public string numruc {
            get {
                return this.numrucField;
            }
            set {
                this.numrucField = value;
                this.RaisePropertyChanged("numruc");
            }
        }
        
        /// <comentarios/>
        public string razoc {
            get {
                return this.razocField;
            }
            set {
                this.razocField = value;
                this.RaisePropertyChanged("razoc");
            }
        }
        
        /// <comentarios/>
        public string estado_cont {
            get {
                return this.estado_contField;
            }
            set {
                this.estado_contField = value;
                this.RaisePropertyChanged("estado_cont");
            }
        }
        
        /// <comentarios/>
        public string condi_dom {
            get {
                return this.condi_domField;
            }
            set {
                this.condi_domField = value;
                this.RaisePropertyChanged("condi_dom");
            }
        }
        
        /// <comentarios/>
        public string ubigeo {
            get {
                return this.ubigeoField;
            }
            set {
                this.ubigeoField = value;
                this.RaisePropertyChanged("ubigeo");
            }
        }
        
        /// <comentarios/>
        public string tipo_via {
            get {
                return this.tipo_viaField;
            }
            set {
                this.tipo_viaField = value;
                this.RaisePropertyChanged("tipo_via");
            }
        }
        
        /// <comentarios/>
        public string nom_via {
            get {
                return this.nom_viaField;
            }
            set {
                this.nom_viaField = value;
                this.RaisePropertyChanged("nom_via");
            }
        }
        
        /// <comentarios/>
        public string cod_zona {
            get {
                return this.cod_zonaField;
            }
            set {
                this.cod_zonaField = value;
                this.RaisePropertyChanged("cod_zona");
            }
        }
        
        /// <comentarios/>
        public string tipo_zona {
            get {
                return this.tipo_zonaField;
            }
            set {
                this.tipo_zonaField = value;
                this.RaisePropertyChanged("tipo_zona");
            }
        }
        
        /// <comentarios/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <comentarios/>
        public string interior {
            get {
                return this.interiorField;
            }
            set {
                this.interiorField = value;
                this.RaisePropertyChanged("interior");
            }
        }
        
        /// <comentarios/>
        public string lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
                this.RaisePropertyChanged("lote");
            }
        }
        
        /// <comentarios/>
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
                this.RaisePropertyChanged("departamento");
            }
        }
        
        /// <comentarios/>
        public string manzana {
            get {
                return this.manzanaField;
            }
            set {
                this.manzanaField = value;
                this.RaisePropertyChanged("manzana");
            }
        }
        
        /// <comentarios/>
        public string kilometro {
            get {
                return this.kilometroField;
            }
            set {
                this.kilometroField = value;
                this.RaisePropertyChanged("kilometro");
            }
        }
        
        /// <comentarios/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <comentarios/>
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <comentarios/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.6.79.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.SoapTypeAttribute(Namespace="urn:ValidaDOCwsdl")]
    public partial class rucDetails : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numrucField;
        
        private string razocField;
        
        private string estado_contField;
        
        private string condi_domField;
        
        private string ubigeoField;
        
        private string tipo_viaField;
        
        private string nom_viaField;
        
        private string cod_zonaField;
        
        private string tipo_zonaField;
        
        private string numeroField;
        
        private string interiorField;
        
        private string loteField;
        
        private string departamentoField;
        
        private string manzanaField;
        
        private string kilometroField;
        
        private string statusField;
        
        private string dniField;
        
        /// <comentarios/>
        public string numruc {
            get {
                return this.numrucField;
            }
            set {
                this.numrucField = value;
                this.RaisePropertyChanged("numruc");
            }
        }
        
        /// <comentarios/>
        public string razoc {
            get {
                return this.razocField;
            }
            set {
                this.razocField = value;
                this.RaisePropertyChanged("razoc");
            }
        }
        
        /// <comentarios/>
        public string estado_cont {
            get {
                return this.estado_contField;
            }
            set {
                this.estado_contField = value;
                this.RaisePropertyChanged("estado_cont");
            }
        }
        
        /// <comentarios/>
        public string condi_dom {
            get {
                return this.condi_domField;
            }
            set {
                this.condi_domField = value;
                this.RaisePropertyChanged("condi_dom");
            }
        }
        
        /// <comentarios/>
        public string ubigeo {
            get {
                return this.ubigeoField;
            }
            set {
                this.ubigeoField = value;
                this.RaisePropertyChanged("ubigeo");
            }
        }
        
        /// <comentarios/>
        public string tipo_via {
            get {
                return this.tipo_viaField;
            }
            set {
                this.tipo_viaField = value;
                this.RaisePropertyChanged("tipo_via");
            }
        }
        
        /// <comentarios/>
        public string nom_via {
            get {
                return this.nom_viaField;
            }
            set {
                this.nom_viaField = value;
                this.RaisePropertyChanged("nom_via");
            }
        }
        
        /// <comentarios/>
        public string cod_zona {
            get {
                return this.cod_zonaField;
            }
            set {
                this.cod_zonaField = value;
                this.RaisePropertyChanged("cod_zona");
            }
        }
        
        /// <comentarios/>
        public string tipo_zona {
            get {
                return this.tipo_zonaField;
            }
            set {
                this.tipo_zonaField = value;
                this.RaisePropertyChanged("tipo_zona");
            }
        }
        
        /// <comentarios/>
        public string numero {
            get {
                return this.numeroField;
            }
            set {
                this.numeroField = value;
                this.RaisePropertyChanged("numero");
            }
        }
        
        /// <comentarios/>
        public string interior {
            get {
                return this.interiorField;
            }
            set {
                this.interiorField = value;
                this.RaisePropertyChanged("interior");
            }
        }
        
        /// <comentarios/>
        public string lote {
            get {
                return this.loteField;
            }
            set {
                this.loteField = value;
                this.RaisePropertyChanged("lote");
            }
        }
        
        /// <comentarios/>
        public string departamento {
            get {
                return this.departamentoField;
            }
            set {
                this.departamentoField = value;
                this.RaisePropertyChanged("departamento");
            }
        }
        
        /// <comentarios/>
        public string manzana {
            get {
                return this.manzanaField;
            }
            set {
                this.manzanaField = value;
                this.RaisePropertyChanged("manzana");
            }
        }
        
        /// <comentarios/>
        public string kilometro {
            get {
                return this.kilometroField;
            }
            set {
                this.kilometroField = value;
                this.RaisePropertyChanged("kilometro");
            }
        }
        
        /// <comentarios/>
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
                this.RaisePropertyChanged("status");
            }
        }
        
        /// <comentarios/>
        public string dni {
            get {
                return this.dniField;
            }
            set {
                this.dniField = value;
                this.RaisePropertyChanged("dni");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validaDNI", WrapperNamespace="urn:ValidaDNIwsdl", IsWrapped=true)]
    public partial class validaDNIRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string key;
        
        public validaDNIRequest() {
        }
        
        public validaDNIRequest(string dni, string key) {
            this.dni = dni;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validaDNIResponse", WrapperNamespace="urn:ValidaDNIwsdl", IsWrapped=true)]
    public partial class validaDNIResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SOAPServices.validaDOC.dniDetails @return;
        
        public validaDNIResponse() {
        }
        
        public validaDNIResponse(SOAPServices.validaDOC.dniDetails @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validaRUC", WrapperNamespace="urn:ValidaRUCwsdl", IsWrapped=true)]
    public partial class validaRUCRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public string dni;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=1)]
        public string key;
        
        public validaRUCRequest() {
        }
        
        public validaRUCRequest(string dni, string key) {
            this.dni = dni;
            this.key = key;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="validaRUCResponse", WrapperNamespace="urn:ValidaRUCwsdl", IsWrapped=true)]
    public partial class validaRUCResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="", Order=0)]
        public SOAPServices.validaDOC.rucDetails @return;
        
        public validaRUCResponse() {
        }
        
        public validaRUCResponse(SOAPServices.validaDOC.rucDetails @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ValidaDOCwsdlPortTypeChannel : SOAPServices.validaDOC.ValidaDOCwsdlPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ValidaDOCwsdlPortTypeClient : System.ServiceModel.ClientBase<SOAPServices.validaDOC.ValidaDOCwsdlPortType>, SOAPServices.validaDOC.ValidaDOCwsdlPortType {
        
        public ValidaDOCwsdlPortTypeClient() {
        }
        
        public ValidaDOCwsdlPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ValidaDOCwsdlPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidaDOCwsdlPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ValidaDOCwsdlPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPServices.validaDOC.validaDNIResponse SOAPServices.validaDOC.ValidaDOCwsdlPortType.validaDNI(SOAPServices.validaDOC.validaDNIRequest request) {
            return base.Channel.validaDNI(request);
        }
        
        public SOAPServices.validaDOC.dniDetails validaDNI(string dni, string key) {
            SOAPServices.validaDOC.validaDNIRequest inValue = new SOAPServices.validaDOC.validaDNIRequest();
            inValue.dni = dni;
            inValue.key = key;
            SOAPServices.validaDOC.validaDNIResponse retVal = ((SOAPServices.validaDOC.ValidaDOCwsdlPortType)(this)).validaDNI(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServices.validaDOC.validaDNIResponse> SOAPServices.validaDOC.ValidaDOCwsdlPortType.validaDNIAsync(SOAPServices.validaDOC.validaDNIRequest request) {
            return base.Channel.validaDNIAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServices.validaDOC.validaDNIResponse> validaDNIAsync(string dni, string key) {
            SOAPServices.validaDOC.validaDNIRequest inValue = new SOAPServices.validaDOC.validaDNIRequest();
            inValue.dni = dni;
            inValue.key = key;
            return ((SOAPServices.validaDOC.ValidaDOCwsdlPortType)(this)).validaDNIAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        SOAPServices.validaDOC.validaRUCResponse SOAPServices.validaDOC.ValidaDOCwsdlPortType.validaRUC(SOAPServices.validaDOC.validaRUCRequest request) {
            return base.Channel.validaRUC(request);
        }
        
        public SOAPServices.validaDOC.rucDetails validaRUC(string dni, string key) {
            SOAPServices.validaDOC.validaRUCRequest inValue = new SOAPServices.validaDOC.validaRUCRequest();
            inValue.dni = dni;
            inValue.key = key;
            SOAPServices.validaDOC.validaRUCResponse retVal = ((SOAPServices.validaDOC.ValidaDOCwsdlPortType)(this)).validaRUC(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<SOAPServices.validaDOC.validaRUCResponse> SOAPServices.validaDOC.ValidaDOCwsdlPortType.validaRUCAsync(SOAPServices.validaDOC.validaRUCRequest request) {
            return base.Channel.validaRUCAsync(request);
        }
        
        public System.Threading.Tasks.Task<SOAPServices.validaDOC.validaRUCResponse> validaRUCAsync(string dni, string key) {
            SOAPServices.validaDOC.validaRUCRequest inValue = new SOAPServices.validaDOC.validaRUCRequest();
            inValue.dni = dni;
            inValue.key = key;
            return ((SOAPServices.validaDOC.ValidaDOCwsdlPortType)(this)).validaRUCAsync(inValue);
        }
    }
}
