//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reclutamiento.MVC.ReclutamientoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rubro", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Rubro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PostulanteAnuncio", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class PostulanteAnuncio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Reclutamiento.MVC.ReclutamientoWS.Anuncio AnuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Reclutamiento.MVC.ReclutamientoWS.Postulante PostulanteField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Reclutamiento.MVC.ReclutamientoWS.Anuncio Anuncio {
            get {
                return this.AnuncioField;
            }
            set {
                if ((object.ReferenceEquals(this.AnuncioField, value) != true)) {
                    this.AnuncioField = value;
                    this.RaisePropertyChanged("Anuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Reclutamiento.MVC.ReclutamientoWS.Postulante Postulante {
            get {
                return this.PostulanteField;
            }
            set {
                if ((object.ReferenceEquals(this.PostulanteField, value) != true)) {
                    this.PostulanteField = value;
                    this.RaisePropertyChanged("Postulante");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Anuncio", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Anuncio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Reclutamiento.MVC.ReclutamientoWS.Empresa EmpresaField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool EstadoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaPublicacionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TituloField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Reclutamiento.MVC.ReclutamientoWS.Empresa Empresa {
            get {
                return this.EmpresaField;
            }
            set {
                if ((object.ReferenceEquals(this.EmpresaField, value) != true)) {
                    this.EmpresaField = value;
                    this.RaisePropertyChanged("Empresa");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Estado {
            get {
                return this.EstadoField;
            }
            set {
                if ((this.EstadoField.Equals(value) != true)) {
                    this.EstadoField = value;
                    this.RaisePropertyChanged("Estado");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaPublicacion {
            get {
                return this.FechaPublicacionField;
            }
            set {
                if ((this.FechaPublicacionField.Equals(value) != true)) {
                    this.FechaPublicacionField = value;
                    this.RaisePropertyChanged("FechaPublicacion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Titulo {
            get {
                return this.TituloField;
            }
            set {
                if ((object.ReferenceEquals(this.TituloField, value) != true)) {
                    this.TituloField = value;
                    this.RaisePropertyChanged("Titulo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Postulante", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Postulante : Reclutamiento.MVC.ReclutamientoWS.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoMaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ApellidoPaternoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DniField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime FechaNacimientoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NombreField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoMaterno {
            get {
                return this.ApellidoMaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoMaternoField, value) != true)) {
                    this.ApellidoMaternoField = value;
                    this.RaisePropertyChanged("ApellidoMaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ApellidoPaterno {
            get {
                return this.ApellidoPaternoField;
            }
            set {
                if ((object.ReferenceEquals(this.ApellidoPaternoField, value) != true)) {
                    this.ApellidoPaternoField = value;
                    this.RaisePropertyChanged("ApellidoPaterno");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Dni {
            get {
                return this.DniField;
            }
            set {
                if ((object.ReferenceEquals(this.DniField, value) != true)) {
                    this.DniField = value;
                    this.RaisePropertyChanged("Dni");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime FechaNacimiento {
            get {
                return this.FechaNacimientoField;
            }
            set {
                if ((this.FechaNacimientoField.Equals(value) != true)) {
                    this.FechaNacimientoField = value;
                    this.RaisePropertyChanged("FechaNacimiento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Nombre {
            get {
                return this.NombreField;
            }
            set {
                if ((object.ReferenceEquals(this.NombreField, value) != true)) {
                    this.NombreField = value;
                    this.RaisePropertyChanged("Nombre");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Empresa : Reclutamiento.MVC.ReclutamientoWS.Usuario {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroRucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Reclutamiento.MVC.ReclutamientoWS.Rubro RubroField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroRuc {
            get {
                return this.NumeroRucField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroRucField, value) != true)) {
                    this.NumeroRucField = value;
                    this.RaisePropertyChanged("NumeroRuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Reclutamiento.MVC.ReclutamientoWS.Rubro Rubro {
            get {
                return this.RubroField;
            }
            set {
                if ((object.ReferenceEquals(this.RubroField, value) != true)) {
                    this.RubroField = value;
                    this.RaisePropertyChanged("Rubro");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Usuario", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Reclutamiento.MVC.ReclutamientoWS.Postulante))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(Reclutamiento.MVC.ReclutamientoWS.Empresa))]
    public partial class Usuario : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Email {
            get {
                return this.EmailField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailField, value) != true)) {
                    this.EmailField = value;
                    this.RaisePropertyChanged("Email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OperationStatus", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class OperationStatus : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<string> MessagesField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool SuccessField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Collections.Generic.List<string> Messages {
            get {
                return this.MessagesField;
            }
            set {
                if ((object.ReferenceEquals(this.MessagesField, value) != true)) {
                    this.MessagesField = value;
                    this.RaisePropertyChanged("Messages");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool Success {
            get {
                return this.SuccessField;
            }
            set {
                if ((this.SuccessField.Equals(value) != true)) {
                    this.SuccessField = value;
                    this.RaisePropertyChanged("Success");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Aptitud", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Aptitud : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="AptitudAnuncio", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class AptitudAnuncio : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Reclutamiento.MVC.ReclutamientoWS.Anuncio AnuncioField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Reclutamiento.MVC.ReclutamientoWS.Aptitud AptitudField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Reclutamiento.MVC.ReclutamientoWS.Anuncio Anuncio {
            get {
                return this.AnuncioField;
            }
            set {
                if ((object.ReferenceEquals(this.AnuncioField, value) != true)) {
                    this.AnuncioField = value;
                    this.RaisePropertyChanged("Anuncio");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Reclutamiento.MVC.ReclutamientoWS.Aptitud Aptitud {
            get {
                return this.AptitudField;
            }
            set {
                if ((object.ReferenceEquals(this.AptitudField, value) != true)) {
                    this.AptitudField = value;
                    this.RaisePropertyChanged("Aptitud");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReclutamientoWS.IReclutamientoService")]
    public interface IReclutamientoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/CrearRubro", ReplyAction="http://tempuri.org/IReclutamientoService/CrearRubroResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Rubro CrearRubro(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/CrearRubro", ReplyAction="http://tempuri.org/IReclutamientoService/CrearRubroResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Rubro> CrearRubroAsync(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ObtenerRubro", ReplyAction="http://tempuri.org/IReclutamientoService/ObtenerRubroResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Rubro ObtenerRubro(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ObtenerRubro", ReplyAction="http://tempuri.org/IReclutamientoService/ObtenerRubroResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Rubro> ObtenerRubroAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ModificarRubro", ReplyAction="http://tempuri.org/IReclutamientoService/ModificarRubroResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Rubro ModificarRubro(int id, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ModificarRubro", ReplyAction="http://tempuri.org/IReclutamientoService/ModificarRubroResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Rubro> ModificarRubroAsync(int id, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/EliminarRubro", ReplyAction="http://tempuri.org/IReclutamientoService/EliminarRubroResponse")]
        void EliminarRubro(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/EliminarRubro", ReplyAction="http://tempuri.org/IReclutamientoService/EliminarRubroResponse")]
        System.Threading.Tasks.Task EliminarRubroAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ListarRubros", ReplyAction="http://tempuri.org/IReclutamientoService/ListarRubrosResponse")]
        System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.Rubro> ListarRubros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ListarRubros", ReplyAction="http://tempuri.org/IReclutamientoService/ListarRubrosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.Rubro>> ListarRubrosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/CrearPostulaciones", ReplyAction="http://tempuri.org/IReclutamientoService/CrearPostulacionesResponse")]
        Reclutamiento.MVC.ReclutamientoWS.OperationStatus CrearPostulaciones(Reclutamiento.MVC.ReclutamientoWS.PostulanteAnuncio postulanteAnuncio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/CrearPostulaciones", ReplyAction="http://tempuri.org/IReclutamientoService/CrearPostulacionesResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.OperationStatus> CrearPostulacionesAsync(Reclutamiento.MVC.ReclutamientoWS.PostulanteAnuncio postulanteAnuncio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ListarPostulaciones", ReplyAction="http://tempuri.org/IReclutamientoService/ListarPostulacionesResponse")]
        System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.PostulanteAnuncio> ListarPostulaciones();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ListarPostulaciones", ReplyAction="http://tempuri.org/IReclutamientoService/ListarPostulacionesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.PostulanteAnuncio>> ListarPostulacionesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/CrearAnuncio", ReplyAction="http://tempuri.org/IReclutamientoService/CrearAnuncioResponse")]
        Reclutamiento.MVC.ReclutamientoWS.OperationStatus CrearAnuncio(Reclutamiento.MVC.ReclutamientoWS.Anuncio anuncio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/CrearAnuncio", ReplyAction="http://tempuri.org/IReclutamientoService/CrearAnuncioResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.OperationStatus> CrearAnuncioAsync(Reclutamiento.MVC.ReclutamientoWS.Anuncio anuncio);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ObtenerAnuncio", ReplyAction="http://tempuri.org/IReclutamientoService/ObtenerAnuncioResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Anuncio ObtenerAnuncio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ObtenerAnuncio", ReplyAction="http://tempuri.org/IReclutamientoService/ObtenerAnuncioResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Anuncio> ObtenerAnuncioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ModificarAnuncio", ReplyAction="http://tempuri.org/IReclutamientoService/ModificarAnuncioResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Anuncio ModificarAnuncio(int id, string titulo, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ModificarAnuncio", ReplyAction="http://tempuri.org/IReclutamientoService/ModificarAnuncioResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Anuncio> ModificarAnuncioAsync(int id, string titulo, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/EliminarAnuncio", ReplyAction="http://tempuri.org/IReclutamientoService/EliminarAnuncioResponse")]
        void EliminarAnuncio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/EliminarAnuncio", ReplyAction="http://tempuri.org/IReclutamientoService/EliminarAnuncioResponse")]
        System.Threading.Tasks.Task EliminarAnuncioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ListarAnuncios", ReplyAction="http://tempuri.org/IReclutamientoService/ListarAnunciosResponse")]
        System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.Anuncio> ListarAnuncios();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ListarAnuncios", ReplyAction="http://tempuri.org/IReclutamientoService/ListarAnunciosResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.Anuncio>> ListarAnunciosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/CrearAptitud", ReplyAction="http://tempuri.org/IReclutamientoService/CrearAptitudResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Aptitud CrearAptitud(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/CrearAptitud", ReplyAction="http://tempuri.org/IReclutamientoService/CrearAptitudResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Aptitud> CrearAptitudAsync(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ObtenerAptitud", ReplyAction="http://tempuri.org/IReclutamientoService/ObtenerAptitudResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Aptitud ObtenerAptitud(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ObtenerAptitud", ReplyAction="http://tempuri.org/IReclutamientoService/ObtenerAptitudResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Aptitud> ObtenerAptitudAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ModificarAptitud", ReplyAction="http://tempuri.org/IReclutamientoService/ModificarAptitudResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Aptitud ModificarAptitud(int id, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ModificarAptitud", ReplyAction="http://tempuri.org/IReclutamientoService/ModificarAptitudResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Aptitud> ModificarAptitudAsync(int id, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/EliminarAptitud", ReplyAction="http://tempuri.org/IReclutamientoService/EliminarAptitudResponse")]
        void EliminarAptitud(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/EliminarAptitud", ReplyAction="http://tempuri.org/IReclutamientoService/EliminarAptitudResponse")]
        System.Threading.Tasks.Task EliminarAptitudAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ListarAptitudes", ReplyAction="http://tempuri.org/IReclutamientoService/ListarAptitudesResponse")]
        System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.Aptitud> ListarAptitudes();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ListarAptitudes", ReplyAction="http://tempuri.org/IReclutamientoService/ListarAptitudesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.Aptitud>> ListarAptitudesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/CrearAptitud_Anuncio", ReplyAction="http://tempuri.org/IReclutamientoService/CrearAptitud_AnuncioResponse")]
        Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio CrearAptitud_Anuncio(int idAnuncio, int idAptitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/CrearAptitud_Anuncio", ReplyAction="http://tempuri.org/IReclutamientoService/CrearAptitud_AnuncioResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio> CrearAptitud_AnuncioAsync(int idAnuncio, int idAptitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ObtenerAptitud_Anuncio", ReplyAction="http://tempuri.org/IReclutamientoService/ObtenerAptitud_AnuncioResponse")]
        Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio ObtenerAptitud_Anuncio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ObtenerAptitud_Anuncio", ReplyAction="http://tempuri.org/IReclutamientoService/ObtenerAptitud_AnuncioResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio> ObtenerAptitud_AnuncioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ModificarAptitud_Anuncio", ReplyAction="http://tempuri.org/IReclutamientoService/ModificarAptitud_AnuncioResponse")]
        Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio ModificarAptitud_Anuncio(int idAnuncio, int idAptitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ModificarAptitud_Anuncio", ReplyAction="http://tempuri.org/IReclutamientoService/ModificarAptitud_AnuncioResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio> ModificarAptitud_AnuncioAsync(int idAnuncio, int idAptitud);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/EliminarAptitud_Anuncio", ReplyAction="http://tempuri.org/IReclutamientoService/EliminarAptitud_AnuncioResponse")]
        void EliminarAptitud_Anuncio(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/EliminarAptitud_Anuncio", ReplyAction="http://tempuri.org/IReclutamientoService/EliminarAptitud_AnuncioResponse")]
        System.Threading.Tasks.Task EliminarAptitud_AnuncioAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ListarAptitudesPorAnuncio", ReplyAction="http://tempuri.org/IReclutamientoService/ListarAptitudesPorAnuncioResponse")]
        System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio> ListarAptitudesPorAnuncio();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ListarAptitudesPorAnuncio", ReplyAction="http://tempuri.org/IReclutamientoService/ListarAptitudesPorAnuncioResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio>> ListarAptitudesPorAnuncioAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReclutamientoServiceChannel : Reclutamiento.MVC.ReclutamientoWS.IReclutamientoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReclutamientoServiceClient : System.ServiceModel.ClientBase<Reclutamiento.MVC.ReclutamientoWS.IReclutamientoService>, Reclutamiento.MVC.ReclutamientoWS.IReclutamientoService {
        
        public ReclutamientoServiceClient() {
        }
        
        public ReclutamientoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReclutamientoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReclutamientoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReclutamientoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Rubro CrearRubro(string descripcion) {
            return base.Channel.CrearRubro(descripcion);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Rubro> CrearRubroAsync(string descripcion) {
            return base.Channel.CrearRubroAsync(descripcion);
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Rubro ObtenerRubro(int id) {
            return base.Channel.ObtenerRubro(id);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Rubro> ObtenerRubroAsync(int id) {
            return base.Channel.ObtenerRubroAsync(id);
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Rubro ModificarRubro(int id, string descripcion) {
            return base.Channel.ModificarRubro(id, descripcion);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Rubro> ModificarRubroAsync(int id, string descripcion) {
            return base.Channel.ModificarRubroAsync(id, descripcion);
        }
        
        public void EliminarRubro(int id) {
            base.Channel.EliminarRubro(id);
        }
        
        public System.Threading.Tasks.Task EliminarRubroAsync(int id) {
            return base.Channel.EliminarRubroAsync(id);
        }
        
        public System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.Rubro> ListarRubros() {
            return base.Channel.ListarRubros();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.Rubro>> ListarRubrosAsync() {
            return base.Channel.ListarRubrosAsync();
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.OperationStatus CrearPostulaciones(Reclutamiento.MVC.ReclutamientoWS.PostulanteAnuncio postulanteAnuncio) {
            return base.Channel.CrearPostulaciones(postulanteAnuncio);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.OperationStatus> CrearPostulacionesAsync(Reclutamiento.MVC.ReclutamientoWS.PostulanteAnuncio postulanteAnuncio) {
            return base.Channel.CrearPostulacionesAsync(postulanteAnuncio);
        }
        
        public System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.PostulanteAnuncio> ListarPostulaciones() {
            return base.Channel.ListarPostulaciones();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.PostulanteAnuncio>> ListarPostulacionesAsync() {
            return base.Channel.ListarPostulacionesAsync();
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.OperationStatus CrearAnuncio(Reclutamiento.MVC.ReclutamientoWS.Anuncio anuncio) {
            return base.Channel.CrearAnuncio(anuncio);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.OperationStatus> CrearAnuncioAsync(Reclutamiento.MVC.ReclutamientoWS.Anuncio anuncio) {
            return base.Channel.CrearAnuncioAsync(anuncio);
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Anuncio ObtenerAnuncio(int id) {
            return base.Channel.ObtenerAnuncio(id);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Anuncio> ObtenerAnuncioAsync(int id) {
            return base.Channel.ObtenerAnuncioAsync(id);
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Anuncio ModificarAnuncio(int id, string titulo, string descripcion) {
            return base.Channel.ModificarAnuncio(id, titulo, descripcion);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Anuncio> ModificarAnuncioAsync(int id, string titulo, string descripcion) {
            return base.Channel.ModificarAnuncioAsync(id, titulo, descripcion);
        }
        
        public void EliminarAnuncio(int id) {
            base.Channel.EliminarAnuncio(id);
        }
        
        public System.Threading.Tasks.Task EliminarAnuncioAsync(int id) {
            return base.Channel.EliminarAnuncioAsync(id);
        }
        
        public System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.Anuncio> ListarAnuncios() {
            return base.Channel.ListarAnuncios();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.Anuncio>> ListarAnunciosAsync() {
            return base.Channel.ListarAnunciosAsync();
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Aptitud CrearAptitud(string descripcion) {
            return base.Channel.CrearAptitud(descripcion);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Aptitud> CrearAptitudAsync(string descripcion) {
            return base.Channel.CrearAptitudAsync(descripcion);
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Aptitud ObtenerAptitud(int id) {
            return base.Channel.ObtenerAptitud(id);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Aptitud> ObtenerAptitudAsync(int id) {
            return base.Channel.ObtenerAptitudAsync(id);
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Aptitud ModificarAptitud(int id, string descripcion) {
            return base.Channel.ModificarAptitud(id, descripcion);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Aptitud> ModificarAptitudAsync(int id, string descripcion) {
            return base.Channel.ModificarAptitudAsync(id, descripcion);
        }
        
        public void EliminarAptitud(int id) {
            base.Channel.EliminarAptitud(id);
        }
        
        public System.Threading.Tasks.Task EliminarAptitudAsync(int id) {
            return base.Channel.EliminarAptitudAsync(id);
        }
        
        public System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.Aptitud> ListarAptitudes() {
            return base.Channel.ListarAptitudes();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.Aptitud>> ListarAptitudesAsync() {
            return base.Channel.ListarAptitudesAsync();
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio CrearAptitud_Anuncio(int idAnuncio, int idAptitud) {
            return base.Channel.CrearAptitud_Anuncio(idAnuncio, idAptitud);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio> CrearAptitud_AnuncioAsync(int idAnuncio, int idAptitud) {
            return base.Channel.CrearAptitud_AnuncioAsync(idAnuncio, idAptitud);
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio ObtenerAptitud_Anuncio(int id) {
            return base.Channel.ObtenerAptitud_Anuncio(id);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio> ObtenerAptitud_AnuncioAsync(int id) {
            return base.Channel.ObtenerAptitud_AnuncioAsync(id);
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio ModificarAptitud_Anuncio(int idAnuncio, int idAptitud) {
            return base.Channel.ModificarAptitud_Anuncio(idAnuncio, idAptitud);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio> ModificarAptitud_AnuncioAsync(int idAnuncio, int idAptitud) {
            return base.Channel.ModificarAptitud_AnuncioAsync(idAnuncio, idAptitud);
        }
        
        public void EliminarAptitud_Anuncio(int id) {
            base.Channel.EliminarAptitud_Anuncio(id);
        }
        
        public System.Threading.Tasks.Task EliminarAptitud_AnuncioAsync(int id) {
            return base.Channel.EliminarAptitud_AnuncioAsync(id);
        }
        
        public System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio> ListarAptitudesPorAnuncio() {
            return base.Channel.ListarAptitudesPorAnuncio();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.List<Reclutamiento.MVC.ReclutamientoWS.AptitudAnuncio>> ListarAptitudesPorAnuncioAsync() {
            return base.Channel.ListarAptitudesPorAnuncioAsync();
        }
    }
}
