//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reclutamiento.MVC.ReclutamientoWS {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Rubro", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Rubro : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DescripcionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Descripcion {
            get {
                return this.DescripcionField;
            }
            set {
                if ((object.ReferenceEquals(this.DescripcionField, value) != true)) {
                    this.DescripcionField = value;
                    this.RaisePropertyChanged("Descripcion");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Empresa", Namespace="http://schemas.datacontract.org/2004/07/SOAPServices.Dominio")]
    [System.SerializableAttribute()]
    public partial class Empresa : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ClaveField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EmailContactoField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NumeroRucField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RazonSocialField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private Reclutamiento.MVC.ReclutamientoWS.Rubro RubroField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Clave {
            get {
                return this.ClaveField;
            }
            set {
                if ((object.ReferenceEquals(this.ClaveField, value) != true)) {
                    this.ClaveField = value;
                    this.RaisePropertyChanged("Clave");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EmailContacto {
            get {
                return this.EmailContactoField;
            }
            set {
                if ((object.ReferenceEquals(this.EmailContactoField, value) != true)) {
                    this.EmailContactoField = value;
                    this.RaisePropertyChanged("EmailContacto");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NumeroRuc {
            get {
                return this.NumeroRucField;
            }
            set {
                if ((object.ReferenceEquals(this.NumeroRucField, value) != true)) {
                    this.NumeroRucField = value;
                    this.RaisePropertyChanged("NumeroRuc");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string RazonSocial {
            get {
                return this.RazonSocialField;
            }
            set {
                if ((object.ReferenceEquals(this.RazonSocialField, value) != true)) {
                    this.RazonSocialField = value;
                    this.RaisePropertyChanged("RazonSocial");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public Reclutamiento.MVC.ReclutamientoWS.Rubro Rubro {
            get {
                return this.RubroField;
            }
            set {
                if ((object.ReferenceEquals(this.RubroField, value) != true)) {
                    this.RubroField = value;
                    this.RaisePropertyChanged("Rubro");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ReclutamientoWS.IReclutamientoService")]
    public interface IReclutamientoService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/CrearRubro", ReplyAction="http://tempuri.org/IReclutamientoService/CrearRubroResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Rubro CrearRubro(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/CrearRubro", ReplyAction="http://tempuri.org/IReclutamientoService/CrearRubroResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Rubro> CrearRubroAsync(string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ObtenerRubro", ReplyAction="http://tempuri.org/IReclutamientoService/ObtenerRubroResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Rubro ObtenerRubro(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ObtenerRubro", ReplyAction="http://tempuri.org/IReclutamientoService/ObtenerRubroResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Rubro> ObtenerRubroAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ModificarRubro", ReplyAction="http://tempuri.org/IReclutamientoService/ModificarRubroResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Rubro ModificarRubro(int id, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ModificarRubro", ReplyAction="http://tempuri.org/IReclutamientoService/ModificarRubroResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Rubro> ModificarRubroAsync(int id, string descripcion);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/EliminarRubro", ReplyAction="http://tempuri.org/IReclutamientoService/EliminarRubroResponse")]
        void EliminarRubro(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/EliminarRubro", ReplyAction="http://tempuri.org/IReclutamientoService/EliminarRubroResponse")]
        System.Threading.Tasks.Task EliminarRubroAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ListarRubros", ReplyAction="http://tempuri.org/IReclutamientoService/ListarRubrosResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Rubro[] ListarRubros();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ListarRubros", ReplyAction="http://tempuri.org/IReclutamientoService/ListarRubrosResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Rubro[]> ListarRubrosAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/CrearEmpresa", ReplyAction="http://tempuri.org/IReclutamientoService/CrearEmpresaResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Empresa CrearEmpresa(string email, string clave, string razonSocial, string numeroRuc, int idRubro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/CrearEmpresa", ReplyAction="http://tempuri.org/IReclutamientoService/CrearEmpresaResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Empresa> CrearEmpresaAsync(string email, string clave, string razonSocial, string numeroRuc, int idRubro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ObtenerEmpresa", ReplyAction="http://tempuri.org/IReclutamientoService/ObtenerEmpresaResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Empresa ObtenerEmpresa(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ObtenerEmpresa", ReplyAction="http://tempuri.org/IReclutamientoService/ObtenerEmpresaResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Empresa> ObtenerEmpresaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ModificarEmpresa", ReplyAction="http://tempuri.org/IReclutamientoService/ModificarEmpresaResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Empresa ModificarEmpresa(int id, string email, string clave, string razonSocial, string numeroRuc, int idRubro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ModificarEmpresa", ReplyAction="http://tempuri.org/IReclutamientoService/ModificarEmpresaResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Empresa> ModificarEmpresaAsync(int id, string email, string clave, string razonSocial, string numeroRuc, int idRubro);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/EliminarEmpresa", ReplyAction="http://tempuri.org/IReclutamientoService/EliminarEmpresaResponse")]
        void EliminarEmpresa(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/EliminarEmpresa", ReplyAction="http://tempuri.org/IReclutamientoService/EliminarEmpresaResponse")]
        System.Threading.Tasks.Task EliminarEmpresaAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ListarEmpresas", ReplyAction="http://tempuri.org/IReclutamientoService/ListarEmpresasResponse")]
        Reclutamiento.MVC.ReclutamientoWS.Empresa[] ListarEmpresas();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IReclutamientoService/ListarEmpresas", ReplyAction="http://tempuri.org/IReclutamientoService/ListarEmpresasResponse")]
        System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Empresa[]> ListarEmpresasAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IReclutamientoServiceChannel : Reclutamiento.MVC.ReclutamientoWS.IReclutamientoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ReclutamientoServiceClient : System.ServiceModel.ClientBase<Reclutamiento.MVC.ReclutamientoWS.IReclutamientoService>, Reclutamiento.MVC.ReclutamientoWS.IReclutamientoService {
        
        public ReclutamientoServiceClient() {
        }
        
        public ReclutamientoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ReclutamientoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReclutamientoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ReclutamientoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Rubro CrearRubro(string descripcion) {
            return base.Channel.CrearRubro(descripcion);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Rubro> CrearRubroAsync(string descripcion) {
            return base.Channel.CrearRubroAsync(descripcion);
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Rubro ObtenerRubro(int id) {
            return base.Channel.ObtenerRubro(id);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Rubro> ObtenerRubroAsync(int id) {
            return base.Channel.ObtenerRubroAsync(id);
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Rubro ModificarRubro(int id, string descripcion) {
            return base.Channel.ModificarRubro(id, descripcion);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Rubro> ModificarRubroAsync(int id, string descripcion) {
            return base.Channel.ModificarRubroAsync(id, descripcion);
        }
        
        public void EliminarRubro(int id) {
            base.Channel.EliminarRubro(id);
        }
        
        public System.Threading.Tasks.Task EliminarRubroAsync(int id) {
            return base.Channel.EliminarRubroAsync(id);
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Rubro[] ListarRubros() {
            return base.Channel.ListarRubros();
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Rubro[]> ListarRubrosAsync() {
            return base.Channel.ListarRubrosAsync();
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Empresa CrearEmpresa(string email, string clave, string razonSocial, string numeroRuc, int idRubro) {
            return base.Channel.CrearEmpresa(email, clave, razonSocial, numeroRuc, idRubro);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Empresa> CrearEmpresaAsync(string email, string clave, string razonSocial, string numeroRuc, int idRubro) {
            return base.Channel.CrearEmpresaAsync(email, clave, razonSocial, numeroRuc, idRubro);
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Empresa ObtenerEmpresa(int id) {
            return base.Channel.ObtenerEmpresa(id);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Empresa> ObtenerEmpresaAsync(int id) {
            return base.Channel.ObtenerEmpresaAsync(id);
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Empresa ModificarEmpresa(int id, string email, string clave, string razonSocial, string numeroRuc, int idRubro) {
            return base.Channel.ModificarEmpresa(id, email, clave, razonSocial, numeroRuc, idRubro);
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Empresa> ModificarEmpresaAsync(int id, string email, string clave, string razonSocial, string numeroRuc, int idRubro) {
            return base.Channel.ModificarEmpresaAsync(id, email, clave, razonSocial, numeroRuc, idRubro);
        }
        
        public void EliminarEmpresa(int id) {
            base.Channel.EliminarEmpresa(id);
        }
        
        public System.Threading.Tasks.Task EliminarEmpresaAsync(int id) {
            return base.Channel.EliminarEmpresaAsync(id);
        }
        
        public Reclutamiento.MVC.ReclutamientoWS.Empresa[] ListarEmpresas() {
            return base.Channel.ListarEmpresas();
        }
        
        public System.Threading.Tasks.Task<Reclutamiento.MVC.ReclutamientoWS.Empresa[]> ListarEmpresasAsync() {
            return base.Channel.ListarEmpresasAsync();
        }
    }
}
